In [4]:
import numpy as np


In [6]:
M = array([[0, 1, 2], [3, 4, 5], [6, 7 ,8]])
M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [11]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\User\Miniconda2\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


False

In [12]:
x=np.random.rand(30)
x

array([ 0.17913703,  0.25268526,  0.2349589 ,  0.4123175 ,  0.52959296,
        0.02584147,  0.16290258,  0.84653871,  0.57235125,  0.22972775,
        0.26175346,  0.62963272,  0.27588052,  0.48631164,  0.80670969,
        0.33869246,  0.31409776,  0.48996102,  0.15787029,  0.04842173,
        0.63747095,  0.94064467,  0.17038315,  0.07825003,  0.71310293,
        0.09103555,  0.9275097 ,  0.01679356,  0.50664506,  0.09053961])

In [13]:
mean(x)

0.38092532980282129

In [14]:
from numpy import random

In [16]:
y=random.rand(5,3)
y

array([[ 0.2625868 ,  0.12135987,  0.80995204],
       [ 0.68050377,  0.57328385,  0.75625668],
       [ 0.18600013,  0.37818564,  0.01002542],
       [ 0.48710637,  0.66254917,  0.3497657 ],
       [ 0.44822111,  0.5886915 ,  0.81341738]])

In [21]:
w=random.rand(3,2)
w

array([[ 0.84094858,  0.59642315],
       [ 0.41566554,  0.1774268 ],
       [ 0.31834196,  0.31928828]])

In [24]:
np.dot(y, w)

array([[ 0.52910883,  0.43675354],
       [ 1.05131125,  0.74904801],
       [ 0.3168068 ,  0.18123605],
       [ 0.79637537,  0.51975158],
       [ 0.88057456,  0.63149373]])

In [42]:
z = np.random.rand(10)
z

array([ 0.33416105,  0.85635831,  0.04758456,  0.82197396,  0.1481039 ,
        0.8123712 ,  0.35807288,  0.94691237,  0.24810654,  0.03512201])

In [43]:
sort(z)

array([ 0.03512201,  0.04758456,  0.1481039 ,  0.24810654,  0.33416105,
        0.35807288,  0.8123712 ,  0.82197396,  0.85635831,  0.94691237])

In [50]:
z1 = np.random.rand(100)
z1

array([ 0.03139722,  0.184591  ,  0.14539729,  0.98424816,  0.81660675,
        0.90350198,  0.35304261,  0.98271902,  0.10082811,  0.27355923,
        0.73627683,  0.26665604,  0.90201689,  0.06478787,  0.79772502,
        0.33742936,  0.19774727,  0.24573457,  0.57215882,  0.80399847,
        0.84929199,  0.16220028,  0.35748818,  0.52130132,  0.90273374,
        0.4052246 ,  0.7904073 ,  0.74102219,  0.75014398,  0.01699982,
        0.5348135 ,  0.94227258,  0.43558826,  0.60891963,  0.48079188,
        0.63396364,  0.99477018,  0.14746334,  0.31494315,  0.65726512,
        0.79164852,  0.76866931,  0.82865473,  0.41294018,  0.79903735,
        0.38862154,  0.66407743,  0.199134  ,  0.02597569,  0.98801088,
        0.09402999,  0.06906071,  0.51604155,  0.33812779,  0.57829282,
        0.71040962,  0.99193697,  0.90734976,  0.60185056,  0.51971251,
        0.17573108,  0.88082119,  0.89256272,  0.6120912 ,  0.87615241,
        0.10543432,  0.29784619,  0.66920617,  0.79570191,  0.36

In [51]:
sort(z1)

array([ 0.01699982,  0.02597569,  0.02865022,  0.03139722,  0.06478787,
        0.06906071,  0.09402999,  0.10082811,  0.10543432,  0.14539729,
        0.14697742,  0.14746334,  0.16220028,  0.17573108,  0.184591  ,
        0.19774727,  0.199134  ,  0.24573457,  0.26665604,  0.27148251,
        0.27355923,  0.29784619,  0.30319623,  0.30343731,  0.30853544,
        0.31121761,  0.31494315,  0.33742936,  0.33812779,  0.35304261,
        0.35748818,  0.35980857,  0.36812591,  0.37493556,  0.37546838,
        0.38862154,  0.4052246 ,  0.40614885,  0.41294018,  0.41701225,
        0.42365125,  0.43558826,  0.48079188,  0.5035836 ,  0.51604155,
        0.51971251,  0.52130132,  0.52801099,  0.5348135 ,  0.57215882,
        0.57829282,  0.58316072,  0.60185056,  0.60459191,  0.60891963,
        0.6120912 ,  0.63396364,  0.63832558,  0.65726512,  0.65842185,
        0.66407743,  0.66920617,  0.68187077,  0.71040962,  0.71512224,
        0.72078772,  0.73627683,  0.74102219,  0.75014398,  0.76

In [52]:
z1[99]=0
z1

array([ 0.03139722,  0.184591  ,  0.14539729,  0.98424816,  0.81660675,
        0.90350198,  0.35304261,  0.98271902,  0.10082811,  0.27355923,
        0.73627683,  0.26665604,  0.90201689,  0.06478787,  0.79772502,
        0.33742936,  0.19774727,  0.24573457,  0.57215882,  0.80399847,
        0.84929199,  0.16220028,  0.35748818,  0.52130132,  0.90273374,
        0.4052246 ,  0.7904073 ,  0.74102219,  0.75014398,  0.01699982,
        0.5348135 ,  0.94227258,  0.43558826,  0.60891963,  0.48079188,
        0.63396364,  0.99477018,  0.14746334,  0.31494315,  0.65726512,
        0.79164852,  0.76866931,  0.82865473,  0.41294018,  0.79903735,
        0.38862154,  0.66407743,  0.199134  ,  0.02597569,  0.98801088,
        0.09402999,  0.06906071,  0.51604155,  0.33812779,  0.57829282,
        0.71040962,  0.99193697,  0.90734976,  0.60185056,  0.51971251,
        0.17573108,  0.88082119,  0.89256272,  0.6120912 ,  0.87615241,
        0.10543432,  0.29784619,  0.66920617,  0.79570191,  0.36

In [53]:
z3=np.random.rand(5,5)
z3

array([[ 0.81886938,  0.78605243,  0.00590151,  0.58915773,  0.6592294 ],
       [ 0.99085549,  0.22029223,  0.29331459,  0.05997116,  0.99145533],
       [ 0.50222365,  0.85644929,  0.47645077,  0.98324881,  0.54085319],
       [ 0.21013241,  0.43923322,  0.50256583,  0.48404983,  0.04134359],
       [ 0.07464919,  0.79252599,  0.49344499,  0.56618883,  0.55550069]])

In [54]:
z3t=z3.T
z3t

array([[ 0.81886938,  0.99085549,  0.50222365,  0.21013241,  0.07464919],
       [ 0.78605243,  0.22029223,  0.85644929,  0.43923322,  0.79252599],
       [ 0.00590151,  0.29331459,  0.47645077,  0.50256583,  0.49344499],
       [ 0.58915773,  0.05997116,  0.98324881,  0.48404983,  0.56618883],
       [ 0.6592294 ,  0.99145533,  0.54085319,  0.04134359,  0.55550069]])

In [58]:
z4 = np.dot(z3,z3t)
z4

array([[ 2.07015054,  1.67520244,  2.02311635,  0.83273384,  1.3867839 ],
       [ 1.67520244,  2.10293693,  1.4212485 ,  0.52239976,  0.97799762],
       [ 2.02311635,  1.4212485 ,  2.47203971,  1.21946455,  1.80849997],
       [ 0.83273384,  0.52239976,  1.21946455,  0.7256674 ,  0.90880855],
       [ 1.3867839 ,  0.97799762,  1.80849997,  0.90880855,  1.50630872]])

In [59]:
diag(z4)

array([ 2.07015054,  2.10293693,  2.47203971,  0.7256674 ,  1.50630872])